ignored:
  - DL3008  # Pin versions in apt-get (acceptable in CI)
  - DL3018  # Pin versions in apk add (acceptable in CI)
  - DL3059  # Multiple consecutive RUN commands allowed for readability
failure-threshold: warning

