# YAML Linting Configuration for Dohodometr
extends: default
rules:
  line-length:
    max: 140
    allow-non-breakable-words: true
  truthy:
    check-keys: false
  indentation:
    indent-sequences: consistent
    indent: 2

  # Indentation
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  # Comments
  comments:
    min-spaces-from-content: 1

  # Document start
  document-start:
    present: false

  # Trailing spaces
  trailing-spaces: enable

  # Empty lines
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1

  # Brackets
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Braces
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
    forbid-empty-values: true

  # Commas
  commas:
    max-spaces-after: 1

  # Colons
  colons:
    max-spaces-before: 0
    max-spaces-after: 1

  # Truthy values
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']

ignore: |
  /.github/
  /node_modules/
  /.venv/
  /venv/
  /.mypy_cache/
  /.pytest_cache/
  /htmlcov/
  /.coverage