# Minimal test compose to support `make ci-test`
name: dohodometr-test

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/investment_db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=test-secret
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: ["pytest", "-v", "--cov=app", "--cov-report=term-missing", "--maxfail=1"]

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: investment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d investment_db"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NODE_ENV=test
    command: ["npm", "run", "test:coverage"]


