# Prometheus Alert Rules for Investment Service
# =====================================================

groups:
  # Infrastructure Alerts
  - name: infrastructure.rules
    rules:
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
          category: infrastructure
        annotations:
          summary: "Service {{ $labels.instance }} is down"
          description: "Service {{ $labels.instance }} has been down for more than 1 minute."
          runbook_url: "https://dohodometr.ru/runbooks/service-down"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 90
        for: 5m
        labels:
          severity: warning
          category: infrastructure
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage is above 90% for more than 5 minutes. Current usage: {{ $value }}%"

      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 85
        for: 10m
        labels:
          severity: warning
          category: infrastructure
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is above 85% for more than 10 minutes. Current usage: {{ $value }}%"

      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 15
        for: 5m
        labels:
          severity: warning
          category: infrastructure
        annotations:
          summary: "Low disk space on {{ $labels.instance }}"
          description: "Disk space is below 15%. Available: {{ $value }}%"

      - alert: DiskSpaceCritical
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 5
        for: 1m
        labels:
          severity: critical
          category: infrastructure
        annotations:
          summary: "Critical disk space on {{ $labels.instance }}"
          description: "Disk space is below 5%. Available: {{ $value }}%"

  # Application Alerts
  - name: application.rules
    rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) * 100 > 5
        for: 5m
        labels:
          severity: critical
          category: application
        annotations:
          summary: "High error rate in {{ $labels.service }}"
          description: "Error rate is above 5% for more than 5 minutes. Current rate: {{ $value }}%"

      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
          category: application
        annotations:
          summary: "High response time in {{ $labels.service }}"
          description: "95th percentile response time is above 2 seconds. Current: {{ $value }}s"

      - alert: DatabaseConnectionsHigh
        expr: pg_stat_activity_count > 80
        for: 5m
        labels:
          severity: warning
          category: database
        annotations:
          summary: "High number of database connections"
          description: "Database connection count is above 80. Current: {{ $value }}"

      - alert: RedisMemoryHigh
        expr: redis_memory_used_bytes / redis_memory_max_bytes * 100 > 90
        for: 5m
        labels:
          severity: warning
          category: database
        annotations:
          summary: "High Redis memory usage"
          description: "Redis memory usage is above 90%. Current: {{ $value }}%"

  # Business Logic Alerts
  - name: business.rules
    rules:
      - alert: FailedImportsHigh
        expr: rate(portfolio_import_failures_total[10m]) > 0.1
        for: 5m
        labels:
          severity: warning
          category: business
        annotations:
          summary: "High rate of failed portfolio imports"
          description: "Portfolio import failure rate is above 0.1/minute. Current rate: {{ $value }}"

      - alert: UserRegistrationFailuresHigh
        expr: rate(user_registration_failures_total[10m]) > 0.05
        for: 5m
        labels:
          severity: warning
          category: business
        annotations:
          summary: "High rate of user registration failures"
          description: "User registration failure rate is above 0.05/minute. Current rate: {{ $value }}"

      - alert: AuthenticationFailuresSpike
        expr: rate(authentication_failures_total[5m]) > 1
        for: 2m
        labels:
          severity: warning
          category: security
        annotations:
          summary: "Spike in authentication failures"
          description: "Authentication failure rate is above 1/minute, possible brute force attack. Rate: {{ $value }}"

  # Security Alerts
  - name: security.rules
    rules:
      - alert: TooManyFailedLogins
        expr: increase(failed_login_attempts_total[5m]) > 50
        for: 0m
        labels:
          severity: critical
          category: security
        annotations:
          summary: "Too many failed login attempts"
          description: "More than 50 failed login attempts in 5 minutes. Possible brute force attack."

      - alert: SuspiciousUserAgent
        expr: increase(suspicious_user_agent_requests_total[10m]) > 10
        for: 0m
        labels:
          severity: warning
          category: security
        annotations:
          summary: "Suspicious user agent detected"
          description: "More than 10 requests with suspicious user agents in 10 minutes."

      - alert: UnauthorizedApiAccess
        expr: rate(unauthorized_api_requests_total[5m]) > 0.5
        for: 2m
        labels:
          severity: warning
          category: security
        annotations:
          summary: "High rate of unauthorized API access"
          description: "Unauthorized API request rate is above 0.5/minute. Rate: {{ $value }}"

  # SSL Certificate Alerts
  - name: ssl.rules
    rules:
      - alert: SSLCertificateExpiringSoon
        expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 7
        for: 0m
        labels:
          severity: warning
          category: security
        annotations:
          summary: "SSL certificate expiring soon"
          description: "SSL certificate for {{ $labels.instance }} expires in less than 7 days."

      - alert: SSLCertificateExpiredOrInvalid
        expr: probe_ssl_earliest_cert_expiry - time() <= 0
        for: 0m
        labels:
          severity: critical
          category: security
        annotations:
          summary: "SSL certificate expired or invalid"
          description: "SSL certificate for {{ $labels.instance }} is expired or invalid."

  # Backup and Data Integrity
  - name: backup.rules
    rules:
      - alert: BackupFailed
        expr: time() - backup_last_success_timestamp > 86400 * 2
        for: 0m
        labels:
          severity: critical
          category: backup
        annotations:
          summary: "Database backup failed"
          description: "Database backup has not completed successfully for more than 2 days."

      - alert: DataIntegrityCheck
        expr: data_integrity_check_failures_total > 0
        for: 0m
        labels:
          severity: critical
          category: data
        annotations:
          summary: "Data integrity check failed"
          description: "Data integrity check has detected {{ $value }} failures."

  # External Dependencies
  - name: external.rules
    rules:
      - alert: ExternalAPIDown
        expr: probe_success{job="blackbox_external_apis"} == 0
        for: 2m
        labels:
          severity: warning
          category: external
        annotations:
          summary: "External API {{ $labels.instance }} is down"
          description: "External API {{ $labels.instance }} has been unreachable for more than 2 minutes."

      - alert: ExternalAPIHighLatency
        expr: probe_duration_seconds{job="blackbox_external_apis"} > 5
        for: 5m
        labels:
          severity: warning
          category: external
        annotations:
          summary: "High latency for external API {{ $labels.instance }}"
          description: "External API {{ $labels.instance }} latency is above 5 seconds. Current: {{ $value }}s"

  # Container and Docker Alerts
  - name: container.rules
    rules:
      - alert: ContainerDown
        expr: absent(container_last_seen{name=~".+"})
        for: 5m
        labels:
          severity: critical
          category: container
        annotations:
          summary: "Container {{ $labels.name }} is down"
          description: "Container {{ $labels.name }} has been down for more than 5 minutes."

      - alert: ContainerMemoryUsageHigh
        expr: (container_memory_usage_bytes / container_spec_memory_limit_bytes) * 100 > 90
        for: 5m
        labels:
          severity: warning
          category: container
        annotations:
          summary: "High memory usage in container {{ $labels.name }}"
          description: "Container {{ $labels.name }} memory usage is above 90%. Current: {{ $value }}%"

      - alert: ContainerCPUUsageHigh
        expr: rate(container_cpu_usage_seconds_total[5m]) * 100 > 80
        for: 10m
        labels:
          severity: warning
          category: container
        annotations:
          summary: "High CPU usage in container {{ $labels.name }}"
          description: "Container {{ $labels.name }} CPU usage is above 80%. Current: {{ $value }}%"

  # Custom Business Metrics
  - name: investment_service.rules
    rules:
      - alert: LowActiveUsers
        expr: active_users_last_24h < 10
        for: 30m
        labels:
          severity: warning
          category: business
        annotations:
          summary: "Low number of active users"
          description: "Number of active users in the last 24 hours is below 10. Current: {{ $value }}"

      - alert: PortfolioCalculationErrors
        expr: rate(portfolio_calculation_errors_total[10m]) > 0.01
        for: 5m
        labels:
          severity: critical
          category: business
        annotations:
          summary: "High rate of portfolio calculation errors"
          description: "Portfolio calculation error rate is above 0.01/minute. Rate: {{ $value }}"

      - alert: TransactionProcessingDelay
        expr: transaction_processing_delay_seconds > 30
        for: 5m
        labels:
          severity: warning
          category: business
        annotations:
          summary: "Transaction processing delay"
          description: "Transaction processing is delayed by more than 30 seconds. Delay: {{ $value }}s"
