name: Deploy Admin to VPS

on:
  workflow_dispatch:
  push:
    branches: [feat/admin-skeleton-import, main]
    paths:
      - 'admin/**'
      - 'docker-compose.admin.yml'
      - 'deploy/nginx/admin.conf'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e
            cd /opt/dohodometr
            if [ -d .git ]; then git pull --rebase; else echo 'Repo not present'; fi
            docker compose -f docker-compose.admin.yml up -d --build
