name: Admin CI

on:
  push:
    paths:
      - 'admin/**'
      - '.github/workflows/admin-ci.yml'
  pull_request:
    paths:
      - 'admin/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('admin/backend/requirements.txt') }}
      - name: Run admin tests
        env:
          ADMIN_TOKEN: test-admin-token
        run: bash admin/ci/run_tests.sh
