name: deprecated-security-workflow

on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow is deprecated and replaced by security-baseline.yml and security-scanning.yml"
